### ISSUE TITLE
question about the test.py

### ISSUE THREAD

**Issue by 1483852602** [kenshohara/3D-ResNets-PyTorch#138]
when calling the test.py, "TypeError: Object of type 'Tensor' is not JSON serializable" .Looking for your reply.

The details are as follows ：
Traceback (most recent call last):
  File "main.py", line 162, in <module>
    test.test(test_loader, model, opt, test_data.class_names)
  File "C:\Users\19649\Desktop\3D-ResNets-PyTorch-master\test.py", line 59, in test
    json.dump(test_results, f)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Tensor' is not JSON serializable

**Comment by wbc0410** [comment]
I got the same question with you and I figured it out today .
You need to change the function calculate_video_results in test.py , by changing the locs into a numpy. Because locs is a Tensor .  

Add the Code below:
locs = locs.numpy()

**Comment by apapadaki** [comment]
The solution to this problem is changing the following lines:
```bash
        video_results.append({
            'label': class_names[locs[i]],
            'score': sorted_scores[i]
        })
```
to:
```bash
        video_results.append({
            'label': class_names[locs[i].item()],
            'score': sorted_scores[i].item()
        })
```
You should use  ```.item()``` because your tensors are 0-dim.
