### ISSUE TITLE
train the densenet . KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by jolly12138** [kenshohara/3D-ResNets-PyTorch#156]
When I use densenet, the following error occurred:
##########################################
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ce870c9191eb>", line 1, in <module>
    runfile('D:/Jolly/keyan/3D-ResNets-PyTorch-master/debug.py', wdir='D:/Jolly/keyan/3D-ResNets-PyTorch-master')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Jolly/keyan/3D-ResNets-PyTorch-master/debug.py", line 64, in <module>
    model, parameters = generate_model(opt)
  File "D:\Jolly\keyan\3D-ResNets-PyTorch-master\model.py", line 147, in generate_model
    sample_duration=opt.sample_duration)
  File "D:\Jolly\keyan\3D-ResNets-PyTorch-master\models\densenet.py", line 17, in densenet121
    **kwargs)
  File "D:\Jolly\keyan\3D-ResNets-PyTorch-master\models\densenet.py", line 182, in __init__
    drop_rate=drop_rate)
  File "D:\Jolly\keyan\3D-ResNets-PyTorch-master\models\densenet.py", line 111, in __init__
    growth_rate, bn_size, drop_rate)
  File "D:\Jolly\keyan\3D-ResNets-PyTorch-master\models\densenet.py", line 75, in __init__
    self.add_module('norm.1', nn.BatchNorm3d(num_input_features))
  File "C:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 180, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'
####################################################

Acoording to the error, wo modify the codes in line 74, 75, 76 and 84, 85,86 in densenet.py 

######################################################
line 74, 75, 76:    norm.1--->norm_1, relu.1--->relu.1, conv.1--->conv_1
line 84, 85, 86:  norm.2--->norm_2, relu.2--->relu.2, conv.2--->conv_2
##############################################

Then this error is sloved. However, when we load the pretrained densenet121 (densenet-121-kinetics.pth), another error is occurred:

###############################################
untimeError: Error(s) in loading state_dict for DataParallel:
Missing key(s) in state_dict: "module.features.denseblock1.denselayer1.norm_1.weight", "module.features.denseblock1.denselayer1.norm_1.bias", "module.features.denseblock1.denselayer1.norm_1.running_mean", "module.features.denseblock1.denselayer1.norm_1.running_var", "module.features.denseblock1.denselayer1.conv_1.weight", "module.features.denseblock1.denselayer1.norm_2.weight", "module.features.denseblock1.denselayer1.norm_2.bias", "module.features.denseblock1.denselayer1.norm_2.running_mean", "module.features.denseblock1.denselayer1.norm_2.running_var", "module.features.denseblock1.denselayer1.conv_2.weight",.........

Unexpected key(s) in state_dict: "module.features.denseblock1.denselayer1.norm.1.weight", "module.features.denseblock1.denselayer1.norm.1.bias", "module.features.denseblock1.denselayer1.norm.1.running_mean", "module.features.denseblock1.denselayer1.norm.1.running_var", "module.features.denseblock1.denselayer1.conv.1.weight", "module.features.denseblock1.denselayer1.norm.2.weight", "module.features.denseblock1.denselayer1.norm.2.bias", "module.features.denseblock1.denselayer1.norm.2.running_mean", "module.features.denseblock1.denselayer1.norm.2.running_var", ..........
#####################################################

It seems the name of the models I bulid is not same as the pretrained.

pytorch 1.0.0

How can I slove it? @kenshohara ?

Can anyone sloved this issue??? Thanks!!

**Comment by Bryce1010** [comment]
After I delete the ‘.',  the code works. But I can't load the pretrained model if I change the model's layer.How to solve this problem?

**Comment by ptirupat** [comment]
Use the following code to load the model. Works with pytorch version 1.2..0
`
def build_densenet_model(trained_model_file, num_classes):
    model = densenet.densenet201(num_classes=num_classes,
                                 sample_size=params.input_size,
                                 sample_duration=params.frames_per_clip)
    pretrained_model = torch.load(trained_model_file)

    pretrained_kvpair = pretrained_model['state_dict']

    model_kvpair = model.state_dict()
    for layer_name, weights in pretrained_kvpair.items():
        if 'classifier' in layer_name:
            continue
        layer_name = layer_name.replace('module.','')
        layer_name = layer_name.replace('.1', '_1').replace('.2','_2')
        model_kvpair[layer_name]=weights   
    model.load_state_dict(model_kvpair)
    return model
`
