### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Bryce1010** [kenshohara/3D-ResNets-PyTorch#159]
I clone the code and use it for my costume data, but I came across following problem.
Thx for your answer.

```shell
> /home/xyang/3D-ResNets-PyTorch/main.py(149)<module>()
    148     ipdb.set_trace()
--> 149     for i in range(opt.begin_epoch, opt.n_epochs + 1):
    150         if not opt.no_train:

ipdb> c                                                                                                  
train at epoch 1
Warning: Input is not to a terminal (fd=13).
> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 

Traceback (most recent call last):
  File "main.py", line 149, in <module>
    for i in range(opt.begin_epoch, opt.n_epochs + 1):
  File "/home/xyang/3D-ResNets-PyTorch/train.py", line 22, in train_epoch
    for i, (inputs, targets) in enumerate(data_loader):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
PermissionError: Traceback (most recent call last):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xyang/3D-ResNets-PyTorch/datasets/medicine.py", line 183, in __getitem__
    path = self.data[index]['video']
  File "/home/xyang/3D-ResNets-PyTorch/datasets/medicine.py", line 183, in __getitem__
    path = self.data[index]['video']
  File "/home/xyang/.conda/envs/py35/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/IPython/core/debugger.py", line 296, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 350, in interaction
    self._cmdloop()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 89, in cmdloop
    line = self.pt_app.prompt() # reset_current_buffer=True)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in prompt
    return run_sync()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/shortcuts/prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 598, in _run_async
    with self.input.attach(read_from_input):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/input/vt100.py", line 147, in _attached_input
    loop.add_reader(fd, callback)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 272, in add_reader
    self.selector.register(fd)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 76, in register
    sel.register(fd)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 131, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
PermissionError: [Errno 1] Operation not permitted


If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
> /home/xyang/3D-ResNets-PyTorch/main.py(149)<module>()
    148     ipdb.set_trace()
--> 149     for i in range(opt.begin_epoch, opt.n_epochs + 1):
    150         if not opt.no_train:

ipdb> c                                                                                                  
train at epoch 1
Warning: Input is not to a terminal (fd=13).
> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 

Traceback (most recent call last):
  File "main.py", line 149, in <module>
    for i in range(opt.begin_epoch, opt.n_epochs + 1):
  File "/home/xyang/3D-ResNets-PyTorch/train.py", line 22, in train_epoch
    for i, (inputs, targets) in enumerate(data_loader):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
PermissionError: Traceback (most recent call last):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xyang/3D-ResNets-PyTorch/datasets/medicine.py", line 183, in __getitem__
    path = self.data[index]['video']
  File "/home/xyang/3D-ResNets-PyTorch/datasets/medicine.py", line 183, in __getitem__
    path = self.data[index]['video']
  File "/home/xyang/.conda/envs/py35/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/IPython/core/debugger.py", line 296, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 350, in interaction
    self._cmdloop()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 89, in cmdloop
    line = self.pt_app.prompt() # reset_current_buffer=True)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in prompt
    return run_sync()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/shortcuts/prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/application/application.py", line 598, in _run_async
    with self.input.attach(read_from_input):
  File "/home/xyang/.conda/envs/py35/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/input/vt100.py", line 147, in _attached_input
    loop.add_reader(fd, callback)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 272, in add_reader
    self.selector.register(fd)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 76, in register
    sel.register(fd)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/site-packages/prompt_toolkit/eventloop/select.py", line 131, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/home/xyang/.conda/envs/py35/lib/python3.5/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
PermissionError: [Errno 1] Operation not permitted


If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 

> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 


Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 

> /home/xyang/3D-ResNets-PyTorch/datasets/medicine.py(183)__getitem__()
    182         ipdb.set_trace()
--> 183         path = self.data[index]['video']
    184 

```

**Comment by iuhiyuh** [comment]
你检查看下是不是你没有数据目录的读取权限

**Comment by Bryce1010** [comment]
> 你检查看下是不是你没有数据目录的读取权限
感谢回复，我调试后发现时多线程的问题，我把num_workers=4改成num_workers=0, 运行主线程后，这个错误消失了。

**Comment by iuhiyuh** [comment]
这个num_workers是进程，而且linux默认多进程是fork主进程，所以可能是你多个进程操作了同一个文件的权限问题。所以可能是你的medicine.py里重写Dataset的__getitem__出问题了。
