### ISSUE TITLE
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1512946747676/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243

### ISSUE THREAD

**Issue by WillDamon** [kenshohara/3D-ResNets-PyTorch#19]
@kenshohara Thanks for your wonderful works and sorry for bothering you.
I try to repeat your work, but there are some problems when I try it. I did not change your code except for the necessary place, Could you please help me to fix this problem? Thank you so much.

The problem is showed as blow:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    opt, train_logger, train_batch_logger)
  File "/home/deep_ww/3D-ResNets-PyTorch-master/train.py", line 29, in train_epoch
    outputs = model(inputs)
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deep_ww/3D-ResNets-PyTorch-master/resnet.py", line 164, in forward
    x = self.fc(x)
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/deep_ww/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1512946747676/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243

**Comment by kenshohara** [comment]
Could you tell me your options?
Did you change the input size from default values?
(--sample_size 112 --sample_duration 16)

**Comment by pkdogcom** [comment]
I think the issue only happens when sample_size is 112 rather than larger size like 224. The cause is that most models in this repository has a spatial stride of 32, while 112 can not be divided by 32, and thus in model initialization (any model's __init__ method) where spatial size of last feature map is calculated by 
```
last_size = int(math.ceil(sample_size / 32))
```
was supposed to convert 112/32=3.5 to the ceiling value 4. However, since sample_size is passed in as integer and thus sample/32 will actually give 3 instead of 3.5 and thus the avgpool layer will have kernel of size (1,3,3) instead of the actual size (1,4,4) and thus leads to the size mismatch error.

Change the last_size calculation to 
```
last_size = int(math.ceil(sample_size / 32.0))
```
can fix the issue.

**Comment by kenshohara** [comment]
Different from python 2.x, a division operator returns float value in Python 3.x
if the results cannot be divided.
So, the operation ```112 / 32``` returns 3.5.
I think that calculation is not a problem.

**Comment by pkdogcom** [comment]
I actually run your code in Python 2.7 and that's why I get the error and I guess he could probably be using the same version as mine.

**Comment by kenshohara** [comment]
I see.
Thank you for your information.
I officially support only Python 3.x.
If you want to use on Python 2.x, you may require some modifications including this problem.
