### ISSUE TITLE
expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by TitaniumOne** [kenshohara/3D-ResNets-PyTorch#212]
```
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main_worker(-1, opt)
  File "main.py", line 388, in main_worker
    train_batch_logger, tb_writer, opt.distributed)
  File "/home/liuhao/testCode/ResNets_3D_PyTorch/training.py", line 33, in train_epoch
    for i, (inputs, targets) in enumerate(data_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liuhao/testCode/ResNets_3D_PyTorch/datasets/videodataset.py", line 145, in __getitem__
    clip = self.__loading(path, frame_indices)
  File "/home/liuhao/testCode/ResNets_3D_PyTorch/datasets/videodataset.py", line 126, in __loading
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: expected a non-empty list of Tensors
```
# In the __gititem__() function, I can print the frame_indices and path correctly, but the clip is empty.

**Comment by liuzhaoo** [comment]
Hi,I got the same error，do youi resolve it？

**Comment by echolijinghui** [comment]
This error means that the model did not get the data, you can check whether the image naming format is like this: 'image_{x:05d}.jpg' if your video_loader is 'VideoLoader()'

**Comment by guilhermesurek** [comment]
I had a similar problem once. Not all files on the annotation list had been downloaded from Youtube (private, removed, etc.) and in the middle of the 1st train loop it crashed. I had to update annotation with the files a had downloaded.
