### ISSUE TITLE
How to execute without GPU

### ISSUE THREAD

**Issue by kpis-msa** [kenshohara/3D-ResNets-PyTorch#225]
My machine has no GPU device.
Then, I have the following message from this engine.

`
Traceback (most recent call last):
  File "main.py", line 428, in <module>
    main_worker(-1, opt)
  File "main.py", line 346, in main_worker
    model = make_data_parallel(model, opt.distributed, opt.device)
  File "/home/********/3D-ResNets-PyTorch/model.py", line 126, in make_data_parallel
    model = nn.DataParallel(model, device_ids=None).cuda()
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 458, in cud
a
    return self._apply(lambda t: t.cuda(device))
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _ap
ply
    module._apply(fn)
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _ap
ply
    module._apply(fn)
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 376, in _ap
ply
    param_applied = fn(param)
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 458, in <la
mbda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 186, in _lazy_i
nit
    _check_driver()
  File "/home/********/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 65, in _check_d
river
    raise AssertionError("""
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
`

Please tell me how to execute this engine without GPU.

**Comment by guilhermesurek** [comment]
Try this flag `--no_cuda`.

**Comment by kpis-msa** [comment]
Thank you
