### ISSUE TITLE
KeyError: 'Biking' when training on UCF101

### ISSUE THREAD

**Issue by N00k0428** [kenshohara/3D-ResNets-PyTorch#238]
python main.py --root_path /test/3D-ResNets-PyTorch/data --video_path ucf101_jpg/ --annotation_path UCF_json/ucf101_01.json \
--result_path results --dataset ucf101 --n_classes 101 --model resnet --model_depth 50 --batch_size 128 \
--n_threads 4 --checkpoint 5 --no_cuda

error result：
dataset loading [0/2293]
Traceback (most recent call last):
  File "main.py", line 429, in <module>
    main_worker(-1, opt)
  File "main.py", line 360, in main_worker
    optimizer, scheduler) = get_train_utils(opt, parameters)
  File "main.py", line 167, in get_train_utils
    spatial_transform, temporal_transform)
  File "/test/3D-ResNets-PyTorch/dataset.py", line 64, in get_training_data
    video_path_formatter=video_path_formatter)
  File "/test/3D-ResNets-PyTorch/datasets/videodataset.py", line 53, in __init__
    root_path, annotation_path, subset, video_path_formatter)
  File "/test/3D-ResNets-PyTorch/datasets/videodataset.py", line 85, in __make_dataset
    label_id = class_to_idx[label]
KeyError: 'Biking'

How should I solve the problem? Thinks！

**Comment by N00k0428** [comment]
json error

**Comment by sebyo** [comment]
what does it mean json error exactly @ltjian-lttj  because I am facing the same error and I don't know what to do
