### ISSUE TITLE
Running on Windows, convert  avi to jpg. FileNotFoundError: [WinError 2] The system cannot find the specified file.

### ISSUE THREAD

**Issue by N00k0428** [kenshohara/3D-ResNets-PyTorch#241]
**(py36) E:\opt\workspace\3D-ResNets-PyTorch-master\util_scripts>python -m generate_video_jpgs \opt\workspace\3D-ResNets-PyTorch-master\data\UCF-101 \opt\workspace\3D-ResNets-PyTorch-master\data\UCF-jpg ucf101**
Traceback (most recent call last):
  File "generate_video_jpgs.py", line 117, in <module>
    for class_dir_path in class_dir_paths)
  File "E:\opt\Anaconda3\envs\py36\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "E:\opt\Anaconda3\envs\py36\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "E:\opt\Anaconda3\envs\py36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "E:\opt\Anaconda3\envs\py36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\opt\Anaconda3\envs\py36\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "E:\opt\Anaconda3\envs\py36\lib\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "E:\opt\Anaconda3\envs\py36\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "generate_video_jpgs.py", line 66, in class_process
    video_process(video_file_path, dst_class_path, ext, fps, size)
  File "generate_video_jpgs.py", line 19, in video_process
    p = subprocess.run(ffprobe_cmd, stdout=PIPE, stderr=PIPE)
  File "E:\opt\Anaconda3\envs\py36\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\opt\Anaconda3\envs\py36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "E:\opt\Anaconda3\envs\py36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
**FileNotFoundError: [WinError 2] The system cannot find the specified file.**

**My structure of data directories is the following:**

E:\opt\workspace\3D-ResNets-PyTorch-master\\
util_scripts\\
……generate_video_jpgs.py
data\\
……UCF_jpg
……UCF-101

**Comment by guilhermesurek** [comment]
I had a few problems with videos in the ActivityNet dataset that could not be downloaded, i.e. it was unavailable on Youtube.
I had to check if the file exists before running the subprocess.
Before this line.
```python
#File "generate_video_jpgs.py", line 19, in video_process
p = subprocess.run(ffprobe_cmd, stdout=PIPE, stderr=PIPE)
```

**Comment by TonyLi-Shu** [comment]
I had the same problem, does anyone solve it?

**Comment by TonyLi-Shu** [comment]
OH, Mine is working right now
1. change it to ===>  p = subprocess.run(ffprobe_cmd,stdout= subprocess.PIPE,shell=True)

2. Do you install the ffmpeg?
I forgot to install the ffmpeg and add it to variable path
When I finish this
now My command is working

**Comment by YTHmamba** [comment]
> OH, Mine is working right now
> 
> 1. change it to ===>  p = subprocess.run(ffprobe_cmd,stdout= subprocess.PIPE,shell=True)
> 2. Do you install the ffmpeg?
>    I forgot to install the ffmpeg and add it to variable path
>    When I finish this
>    now My command is working
@TonyLi-Shu 
hello,Did you download it under Windows?

**Comment by ECHOSPARK** [comment]
> 2\. ffmpeg



> OH, Mine is working right now
> 
> 1. change it to ===>  p = subprocess.run(ffprobe_cmd,stdout= subprocess.PIPE,shell=True)
> 2. Do you install the ffmpeg?
>    I forgot to install the ffmpeg and add it to variable path
>    When I finish this
>    now My command is working

I have solved this problem by installing "ffmpeg"
