### ISSUE TITLE
Performance of pretrained weights on UCF101

### ISSUE THREAD

**Issue by MohsenFayyaz89** [kenshohara/3D-ResNets-PyTorch#33]
Hi,
Nice work! I have a question about your results on UCF101 split 1. I've evaluated your pretrained weight of "resnext-101-kinetics-ucf101_split1.pth" on UCF101 split 1 and got the accuracy of ~85.99. I'm wondering if it is the right accuracy or not. Would you please provide the accuracies of the pretrained models?

**Comment by chandnikathuria1992** [comment]
when i tried to run command:
python main.py --root_path ~/data --video_path ucf101_videos/jpg --annotation_path ucf101_01.json
--result_path results --dataset ucf101 --n_classes 400 --n_finetune_classes 101
--pretrain_path models/resnet-34-kinetics-cpu.pth --ft_begin_index 4
--model resnet --model_depth 34 --resnet_shortcut A --batch_size 128 --n_threads 4 --checkpoint 5

i have also set no_cuda=True in opts as i m running it on cpu only**

I m getting this error:

Traceback (most recent call last):
File "HAR_3D/main.py", line 47, in
model, parameters = generate_model(opt)
File "/home/chandni/HAR_3D/model.py", line 178, in generate_model
model.load_state_dict(pretrain['state_dict'])
File "/home/chandni/anaconda3/envs/har/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
.format(name))
KeyError: 'unexpected key "module.conv1.weight" in state_dict'
Can u help on this?

**Comment by MohsenFayyaz89** [comment]
@chandnikathuria1992 It seems that your pretrained weights and model are not consistent. However, I'm not sure why you're facing it. It seems that the command is right.

**Comment by chandnikathuria1992** [comment]
U r running this on single GPU machine or multiple GPUs?
Can u specify the options u passed to run the code?

**Comment by kenshohara** [comment]
@MohsenFayyaz89 

When I evaluated the model, the clip accuracy for validation set (accuracy in val.log) is 86.2%,
and the video accuracy (evaluating val.json) is 90.1%.
If you mean the accuracy is clip accuracy, the accuracy is right.

**Comment by MohsenFayyaz89** [comment]
@kenshohara 
Thank you very much!
And may I ask you how do you evaluate the video accuracy (val.json)? I couldn't find the option on your code.

**Comment by kenshohara** [comment]
I will add the evaluation scripts in utils later.
Please wait a moment.

**Comment by MohsenFayyaz89** [comment]
@kenshohara Hi, any news about the evaluation scripts?

**Comment by kenshohara** [comment]
I added the evaluation scripts in utils.
Their usages are the same as official evaluation scripts for activitynet.

```
kinetics_classification = KINETICSclassification('kinetics.json', 'val.json', subset='validation', top_k=1)
kinetics_classification.evaluate()
print(kinetics_classification.hit_at_k)
```

```
ucf_classification = UCFclassification('ucf101_01.json', 'val.json', subset='validation', top_k=1)
ucf_classification.evaluate()
print(ucf_classification.hit_at_k)
```

**Comment by MohsenFayyaz89** [comment]
@kenshohara Thanks

**Comment by alidiba67** [comment]
Hi @kenshohara,
I think there are some missing classes in utils.py.
Once, I want to try the eval scripts, there are errors for these lines:

from utils import get_blocked_videos
from utils import interpolated_prec_rec

Could you please update utils.py?

Thanks

**Comment by kenshohara** [comment]
Sorry, I fixed the problem.
Please try it again.

**Comment by alidiba67** [comment]
@kenshohara Thanks.
Also there is an issue in dataset.py for kinetics get_test_set:
you called sample_stride in line 112 which is not set in opt.py and also not used in kinetics.py

**Comment by zy486at189cn** [comment]
@chandnikathuria1992 you should use like this: python3 main.py --root_path ~/project/S_L-ResNet --video_path S_LJPG --annotation_path S_Ljson/S_L.json --result_path results --dataset kinetics --model resnet --model_depth 34 --resnet_shortcut A --n_classes 400 --batch_size 30 --n_threads 4 --checkpoint 5
the param  --resnet_shortcut A solute my problem just like yours.

**Comment by NasimKhani** [comment]
Hi, sorry How should I execute the code to evaluated your pretrained weight of "resnext-101-kinetics-ucf101_split1.pth" on UCF101 split 1 ?

**Comment by guybenyosef** [comment]
@alidiba67 @kenshohara,
is the problem with "sample_stride in line 112 which is not set in opt.py" solved? I"m having a similar error, 
Thanks!

**Comment by RyanCV** [comment]
@kenshohara @MohsenFayyaz89  In the end of code `eval_ucf101.py`, I add 
```
if __name__ == '__main__':
    #pdb.set_trace()
    ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1)
    ucf_classification.evaluate()
    print(ucf_classification.hit_at_k)
```
But, I got the following errors, how to solve it? thanks.
`3D-ResNets-PyTorch# python utils/eval_ucf101.py`

> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   return f(*args, **kwds)
> Traceback (most recent call last):
>   File "utils/eval_ucf101.py", line 164, in <module>
>     ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1)
>   File "utils/eval_ucf101.py", line 23, in __init__
>     ground_truth_filename)
>   File "utils/eval_ucf101.py", line 59, in _import_ground_truth
>     for videoid, v in data['database'].iteritems():
> AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by RyanCV** [comment]
I find the solution:
need to change `for videoid, v in data['database'].iteritems():`
`for videoid, v in data['database'].items(): `for python3

**Comment by Mohamad73** [comment]
Hello everybody, 
where do i get the ucf101_01.json from?

**Comment by Mohamad73** [comment]
Hi, I am getting this error, can anybody help plz?
`python3 eval_ucf101.py 
Traceback (most recent call last):
  File "eval_ucf101.py", line 157, in <module>
    ucf_classification = UCFclassification('data/ucf101_01.json', 'data/results/val.json', subset='validation', top_k=1)
  File "eval_ucf101.py", line 22, in __init__
    self.prediction = self._import_prediction(prediction_filename)
  File "eval_ucf101.py", line 92, in _import_prediction
    for videoid, v in data['results'].items():
TypeError: list indices must be integers or slices, not str
`

**Comment by sumeetssaurav** [comment]
Hii, Did anyone noticed the val.json is containing prediction for 1 video less than that present in the validation set. Like if I have 100 validation samples in the UCF101_01.json, then the val.json only contain prediction results of 99 samples. Please help me in rectifying the issue.

**Comment by ibsakum** [comment]
Hi sumeetssaurav  where did you get val.json file

**Comment by apapadaki** [comment]
> Hi sumeetssaurav where did you get val.json file

You would have to include ``` --no_train --no_val --test --test_subset val ``` in your command.

For example:
```bash
python3 main.py --root_path /Kinetics/ --video_path val_400_jpg/ --annotation_path kinetics.json --result_path result --dataset kinetics --model resnet --model_depth 18 --n_classes 400 --n_threads 4 --resume_path results/resnet-18-kinetics.pth --no_train --no_val --test --test_subset val --n_finetune_classes 400 --resnet_shortcut A
```
Don't forget to adjust the following: ```--root_path```, ```--video_path```,```--annotation_path```, ```--resume_path``` to fit your dataset and your files location.

**Comment by bragilee** [comment]
@MohsenFayyaz89 
Hi,

Is that possible to know your settings? Did you finetune the model? I tried to evaluate using the same model on UCF101 but got nothing. There might be something wrong. 
I just downloaded pre-trained model and run followings commands:

python3.6 main.py --root_path /media/runze/raid/Research/3D-ResNets-PyTorch/data/ucf101_videos --video_path /media/runze/raid/Research/3D-ResNets-PyTorch/data/ucf101_videos/jpg --annotation_path /media/runze/raid/Research/3D-ResNets-PyTorch/data/ucf101_videos/ucf101_01.json --result_path results --dataset ucf101 --n_classes 101 --n_finetune_classes 101 --pretrain_path models/resnext-101-64f-kinetics-ucf101_split1.pth --ft_begin_index 4 --model resnext --model_depth 101 --resnet_shortcut B --batch_size 16 --n_thread 2 --checkpoint 5 --test --test_subset val --no_train --no_val

Thank you so much. :)
