### ISSUE TITLE
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:243

### ISSUE THREAD

**Issue by cynwpu** [kenshohara/3D-ResNets-PyTorch#34]
In the experiment of fine-tuning conv5_x and fc layers of a pretrained model on UCF-101. I got a size mismatch error. I have checked the shape of UCF-101 input data is (128L, 3L, 16L, 112L, 112L). 

Complete error message:
`Traceback (most recent call last):
  File "main.py", line 140, in <module>
    train_logger, train_batch_logger)
  File "/home/magic/yc/ActionRecognition/3D-ResNets-PyTorch-master/train.py", line 34, in train_epoch
    outputs = model(inputs)
  File "/home/magic/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/magic/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/magic/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 70, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/magic/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:243`

My command:
`python main.py --root_path ./data --video_path UCF101/jpg --annotation_path ucf101_01.json --result_path results --dataset ucf101 --n_classes 400 --n_finetune_classes 101 --pretrain_path models/resnet-34-kinetics.pth --ft_begin_index 4 --model resnet --model_depth 34 --resnet_shortcut A --batch_size 128 --n_threads 4 --checkpoint 5`

**Comment by kenshohara** [comment]
Please see this issue #19.
I do not officially support python2.

**Comment by cynwpu** [comment]
@kenshohara Thank you
