### ISSUE TITLE
Continue training on fine-tune model

### ISSUE THREAD

**Issue by vateye** [kenshohara/3D-ResNets-PyTorch#42]
I have used the code to fine-tune on hmdb51, I use the following command.
`python main.py --root_path ~/Research/datasets --video_path hmdb51/jpg --annotation_path hmdb51/testTrainMulti/hmdb51_1.json --result_path ~/Research/3D-ResNets-PyTorch/results/hmdb51 --dataset hmdb51 --n_classes 400 --n_finetune_classes 51 --pretrain_path ~/Research/3D-ResNets-PyTorch/pretrain/resnext-101-kinetics.pth --ft_begin_index 5 
--model resnext --model_depth 101 --resnet_shortcut B --resnext_cardinality 32 --batch_size 32 --n_threads 4 --checkpoint 5 --n_epochs 20`

After training, I got 'save_20.pth' weight, then I run the following code to continue training from 21st epochs.
`python main.py --root_path ~/Research/datasets --video_path hmdb51/jpg --annotation_path hmdb51/testTrainMulti/hmdb51_2.json --result_path ~/Research/3D-ResNets-PyTorch/results/hmdb51 --dataset hmdb51 --n_finetune_classes 51 --n_classes 51 --resume_path ~/Research/3D-ResNets-PyTorch/results/hmdb51/save_20.pth --model resnext --model_depth 101 --resnet_shortcut B --resnext_cardinality 32 --batch_size 32 --n_threads 4 --checkpoint 5 --n_epochs 20`

I got an error: 
`Traceback (most recent call last):
  File "main.py", line 131, in <module>
    optimizer.load_state_dict(checkpoint['optimizer'])
  File "/home/ole/anaconda3/lib/python3.6/site-packages/torch/optim/optimizer.py", line 87, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups `

How can I fix this?

**Comment by kenshohara** [comment]
You should execute as the following.
```
python main.py --root_path ~/Research/datasets --video_path hmdb51/jpg --annotation_path hmdb51/testTrainMulti/hmdb51_2.json --result_path ~/Research/3D-ResNets-PyTorch/results/hmdb51 --dataset hmdb51 --n_classes 400 --n_finetune_classes 51 --pretrain_path ~/Research/3D-ResNets-PyTorch/pretrain/resnext-101-kinetics.pth --resume_path ~/Research/3D-ResNets-PyTorch/results/hmdb51/save_20.pth --ft_begin_index 5 --model resnext --model_depth 101 --resnet_shortcut B --resnext_cardinality 32 --batch_size 32 --n_threads 4 --checkpoint 5 --n_epochs 20
```

**Comment by oOlivero** [comment]
Hi, I have the same question, after I've tried the following code on my training. I got an error
`run
train at epoch 21
Epoch: [21][1/224]      Time 18.938 (18.938)    Data 17.811 (17.811)    Loss 7.7439 (7.7439)    Acc 0.000 (0
.000)
Epoch: [21][2/224]      Time 0.583 (9.761)      Data 0.032 (8.922)      Loss 7.1572 (7.4506)    Acc 0.062 (0
.031)
Epoch: [21][3/224]      Time 0.569 (6.697)      Data 0.016 (5.953)      Loss 8.0857 (7.6623)    Acc 0.000 (0
.021)
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *,
 Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block:
[0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generated/../THCReduceAll.cuh line=339 error=59 : device-side a
ssert triggered
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    train_logger, train_batch_logger)
  File "/media/ole/000BB7550005DEB1/Research/3D-ResNets-PyTorch/train.py", line 31, in train_epoch
    acc = calculate_accuracy(outputs, targets)
  File "/media/ole/000BB7550005DEB1/Research/3D-ResNets-PyTorch/utils.py", line 58, in calculate_accuracy
    n_correct_elems = correct.float().sum().data[0]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generated/../
THCReduceAll.cuh:339
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStora
ge.c:184`

**Comment by kenshohara** [comment]
@oOlivero Your error is not the same as this issue.
#41 is the same as yours.
Please move to #41.

**Comment by oOlivero** [comment]
@kenshohara But I run the same script as you provided. Then I got that error.

**Comment by kenshohara** [comment]
I know you ran my script.
I said your error message is not the same as the error message of this issue #42.
Your error is related to the error message in #41.
